spring.application.name=FinanceFlowBackend

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:financeflow.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Security - JWT
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2c34afef683eefac86b97b10292882f05
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.financeflow.backend=DEBUG
